### ISSUE TITLE
Parents not receiving confirmation emails -- need an alternative

### ISSUE THREAD

**Issue by zminster** [Spark-Hackathon/registration#22]
I'm getting a lot of emails from parents asking for status updates even though we've already approved them. Two parts to this one:

1. To give them a link to their status page, I have to pull the uuid from the db. An endpoint that takes camper ID and gives me status uuid link would be fine.
2. It would be excellent if parents could type in name/email on a status check page and have it redirect to the correct status page automatically. This would mitigate problems with email transmission.

I'm curious why the emails aren't going through, but I'm sure they're being marked as spam. Not much we can do about that except design around it.

**Comment by charlie-map** [comment]
There is a now a route at `/redirect-status-page` that takes in: {`first_name`, `last_name`, `email`} and redirects them to their status page. This is currently set up on backend but needs a small frontend page for login.

**Comment by charlie-map** [comment]
There is now a front-end page at [`/status-page`](https://summerspark.stab.org/status-page). This could be sent to any camper unable to access their page.
