### ISSUE TITLE
Need way to send logistics emails to in-person and virtual campers separately

### ISSUE THREAD

**Issue by zminster** [Spark-Hackathon/registration#24]
Should have some kind of admin-facing radio buttons for registered only: "BOTH" / "VIRTUAL" / "IN-PERSON" so we can send instructions / logistics info to campers separately.

**Comment by charlie-map** [comment]
Competed - going to `/admin` and scrolling down to Send Mail, there is now a selection for: send only to in-person, send only to online, or both.
