### ISSUE TITLE
Post-Approval Flow

### ISSUE THREAD

**Issue by zminster** [Spark-Hackathon/registration#9]
Use this space to muse about the UI/UX and general flow of the user interactions post-registration.

What happens upon approval? (Email sent with unique code, taken to "manage my camp weeks" -- this needs to be fleshed out).

"Manage my camp weeks" screen needs to flow through to health data & consent/release conditionally based on in-person / virtual choice. If these choices change, form data needs to appear / be removed from the db.

Health data and C&R will need to be separated UI components -- this means they could also be totally "separate steps." Need a data definition for this (C&R is just a boolean flag and a datetime when signed; health data is a lot -- needs to be fleshed out to a pretty significant degree. Will probably meet with @charlie-map to discuss layout).

**Comment by zminster** [comment]
With changes in ae86ee2af8d2e1daab55a3557026ff913b8e4afa and 0f66b25b6e1feea8206400697e89cd5b2a42b714, the current route for "manage my camp weeks" is `/reg-status?camper_id=XX`, where `camper_id` is a UUID mapped to campers (unchanging).

We want to provide functionality for:
- Viewing current status of each week (applied / approved / confirmed -- see #13, perhaps "confirmed" means the camper has confirmed attendance, or does it just mean they filled out forms?) [requires non-UI data endpoint for dynamic fill, or could do hbs template fill -- would say that you could un-enroll via a button reload the data without reloading the page using a lazy-loaded endpoint, which would also support async dev during this time period]
- Un-enrolling from a week (works whether applicant or approved) [requires UI'd endpoint]
- Changing week preference (in-person / virtual) [requires UI'd endpoint]
- Filling out OR editing health & C/R forms (once at least one week is approved) [requires grokking]

Current milestone roll (reg-only) requires just a status view that reads "applied" for each week.

**Comment by charlie-map** [comment]
The idea of having a way of editing the forms seems to contrast the safety aspect we're going for; if we give users a way to edit and change their current health data, then we have to consider the fact that both public and private key must be in the .env file, suggesting that if there was a break in, then said person would automatically have both keys needed for viewing this information

**Comment by charlie-map** [comment]
They have the ability to fill out any health forms. This is all available on their `/get-status` page which also gives them their status for weeks (in-person or virtual, approved or applie, etc.).
